## $$Convolución$$ ##

Sirve para el tratamiento de señales, busqueda de petroleo, busqueda de minerales, etc.  
Existen 2 tipos según a la naturaleza de la función:
* Convolución en tiempo continuo.
* Convolución en tiempo discreto.
### $1.-Convolución\:en\:Tiempo\:Continuo\:(Integral\:Convolución)$ ###
$$f(t)*g(t)=\int_{-\infty}^{\infty}f(\tau)g(t-\tau)d\tau$$
Para evaluar esta integral para un valor específico de t, se fija la señal $h(t-\tau)$ ( mediante considerada como función de $\tau$ con t fija) a partir de h($\tau$) un reflejo alrededor del origen y corrimiento a la derecha en un valor t si t>0 o a la izquiera por |t| para t<0.
![Image](Imagenes/convolucion.PNG)

Una forma de entender la convolución se puede hacer a traves de un **INTERPRETACIÓN GRÁFICA**, de la siguiente manera:
![GIF](https://upload.wikimedia.org/wikipedia/commons/4/42/Convolucion_de_entrada_con_respuesta_al_impulso.gif)
**RECORDAR:**  
Existen diversas formas de obtener la convolución entre funciones.

## $3- Polinomios$ ##
Son expresiones de suma de variables, donde podemos encontrar uno o más variables con coeficientes positivos o negativos.

$$f(x)=x^2+2x+1$$
o tambien
$$f(x,y)=2x^4-4x^2y+3xy^2+8y^2+5$$

In [23]:
from IPython.display import Image
from scipy import signal
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
from scipy.fftpack import fft, ifft

In [2]:
%matplotlib notebook

In [5]:
coef=[1,2,1] #Coeficientes del polinomio
px=np.poly1d(coef)
a=3 #valor a evaluar en el polinomio
print(px)
print(f'El valor de f({a})={px(a)}')

   2
1 x + 2 x + 1
El valor de f(3)=16


In [8]:
pxy=lambda x,y:2*x**4-(4*x**2)*y+3*x*y**2+8*y**2+5
#esta manera es la más conocida llamada "función desconocida"
a,b=3,0 #valor a evaluar en la expresión
print(pxy(a,b)) #la salida del valor

167


## $3.1-Representación\:Polinomio\:de\:una\:Variable$ ##
por lo general un polinomio se pued\:Polinomio\:Y\:Convolución\:Lineale representar de la siguiente manera:
$$f(x)=a_0+a_1x+a_2x^2+...+a_{n-1}x^{n-1}$$
de forma resumida:
$$f(x)=\sum_{i=0}^{n-1}a_ix^i$$
Donde: el vector de coeficientes es $[a_0,a_1,a_2,...,a_{n-1}]$
## $3.2-Multiplicación\:de\:Polinomio\:Y\:Convolución\:Lineal$ ##
La estrategia está en trabajar con los vectores de coeficientes de los polinomios.
$$p(x)=a_0+a_1x+a_2x^2+...+a_nx^n$$
$$q(x)=b_0+b_1x+b_2x^2+...+b_mx^m$$
El producto de polinomios es
$$p(x).q(x)=a_0b_0+(a_1b_0+b_1a_0)x+...+a_nb_mx^{m+n}$$
el vector de coeficiente:
$$(p*q)(x)=a.b=[c_0,c_1,...,c_{n+m}]$$
Finalmente se representa como:
$$c[k]=\sum_{i=-\infty}^{\infty}a[i]b[k-i]\:k=0,1,...,n+m$$
Esta operación hace referencia a **convolución lineal** que se denota con "*".  
**Nota:** Si el polinomio tiene N y M terminos, la multiplicación tendrá N+M-1 terminos.

## $3.2-Matriz\:TOEPLITZ\:Y\:CONVOLUCIÓN$ ##
La operación de convolución de 2 secuencias puede verse como una multiplicación de matrices. Dado un tiempo LTI con respuesta h[n] y una secuencia de entrada x[n] la salida del sistema será y[n].
$$y[k]=h[n]*x[n]=\sum_{i=-\infty}^{\infty}x[i]h[k-i]$$
Un ejemplo, x[n] y h[n] tienen N y M elementos respectivamente, la convolución será:
$$y[k]=h[n]*x[n]=\sum_{i=-\infty}^{\infty}x[i]h[k-i]\:k=0,1,...,5$$
La representación de la ecuación en matriz será:
$$y=h*x=\begin{pmatrix}
   h_0 & 0 & 0 \\
   h_1 & h_0 & 0 \\
   h_2 & h_1 & h_0 \\
   h_3 & h_2 & h_1 \\
   0 & h_3 & h_2 \\
   0 & 0 & h_3 \\
   \end{pmatrix}
   \begin{pmatrix}
   x_0 \\
   x_1 \\
   x_2 \\
   \end{pmatrix}
$$
La matriz con retrasos incrementales de h[n] es la **MATRIZ TOEPLITZ**.   
**NOTA:** La matriz TOEPLITZ llamada matriz circulante se usa en aplicaciones de convolución circular y Transforma Discreta de Fourier (DFT).
$$T(h)=\begin{pmatrix}
   h_0 & 0 & 0 \\
   h_1 & h_0 & 0 \\
   h_2 & h_1 & h_0 \\
   h_3 & h_2 & h_1 \\
   0 & h_3 & h_2 \\
   0 & 0 & h_3 \\
   \end{pmatrix}$$

## $4-Métodos\:para\:calcular\:Convolución$ ##
Dado un sistema LTI con respuesta al impulso h[n] y una secuencia de entrada x[n].
$$y[k]=h[n]*x[n]=\sum-{i=-\infty}^{\infty}x[i]h[k-i]$$
### $4.1-Método Fuerza Bruta$ ###
La ecuación de convolución se simplifica a la interpretación de multiplicación de funciones.

In [14]:
def conv_fuerza_bruta (x,h):
    N, M=len(x), len(h)
    y=np.zeros(N+M-1)
    for i in range(N):
        for j in range(M):
            y[i+j-1]=y[i+j-1]+x[i]*h[j]
    
    return y

In [15]:
coef_h=[1,2,1,3] #la representación es h3,h2,...
coef_x=[1,4,-1] #la representación es x3,x2,...
print('Polinomios:')
print(np.poly1d(coef_h),end='\n')
print(np.poly1d(coef_x))
print('convolución:')
coef_inv_h=coef_h[::-1]
coef_inv_x=coef_x[::-1]
convol=conv_fuerza_bruta(coef_inv_x,coef_inv_h)
print(convol)

Polinomios:
   3     2
1 x + 2 x + 1 x + 3
   2
1 x + 4 x - 1
convolución:
[11.  5.  8.  6.  1. -3.]


### $4.2-Método\:Matriz\:Toeplitz$ ###
Cuando la secuencia de h[n] y x[n] son representado en matrices, la operación de convolución se puede representar como:
$$y=h*x=T(h)*X$$
Donde: **la matriz Toeplitz T(h) es de tamaño (N+p-1)x(p), p es la longitud de x.**

In [20]:
h=np.array([[1,0,1,2],[1,5,-1,2],[3,2,-5,1]])
x=np.array([[1,0,0,0],[2,0,0,0],[3,0,0,0],[4,0,0,0]])
y=signal.convolve(x,h)

print(y)

[[  1   0   1   2   0   0   0]
 [  3   5   1   6   0   0   0]
 [  8  12  -4  11   0   0   0]
 [ 13  19  -9  16   0   0   0]
 [ 13  26 -19  11   0   0   0]
 [ 12   8 -20   4   0   0   0]]


### $4.3-Método\:FFT$ ###
Calcula la convolución usando la FFT, reduce calculos complejos cuando los  vectores de entrada son largos.  
**NOTA:** La FFT se manifiesta como convolución circular en el dominio del tiempo, pero nosotros queremos el calculo en  convolución lineal, por ello se realizará de la siguiente manera:
$$y[n]=IFFT[FFT_L(x).FFT_L(h)],\:\:2^L\geq |N+M-1|$$
este calculo es ineficiente porque me agrega zeros de relleno.  
Por ello, el siguiente algoritmo, que ignora ceros adicionales en los términos de salida, es suficiente.
$$y[n]=IFFT[FFT_L(x).FFT_L(h)],\:\:L=N+M-1$$

In [45]:
x=np.random.randn(1,7)+1j*np.random.randn(1,7)
h=np.random.randn(1,3)+1j*np.random.randn(1,3)
L=x.size+h.size-1

y1=signal.convolve(x,h)
y2=ifft(fft(x,L)*fft(h,L), L)
y3=signal.convolve(x, h, method='fft')
print(y1,'\n')
print(y2,'\n')
print(y3,'\n')

[[ 2.26068585-0.57577362j -0.62590069+0.2024537j  -6.33331777+1.66715148j
   6.95674365-2.06146729j  3.60918254+0.08356593j -5.93251879+2.08605328j
   0.58780338-0.73765227j  4.6115309 -1.32716014j -4.64853451+1.73270074j]] 

[[ 2.26068585-0.57577362j -0.62590069+0.2024537j  -6.33331777+1.66715148j
   6.95674365-2.06146729j  3.60918254+0.08356593j -5.93251879+2.08605328j
   0.58780338-0.73765227j  4.6115309 -1.32716014j -4.64853451+1.73270074j]] 

[[ 2.26068585-0.57577362j -0.62590069+0.2024537j  -6.33331777+1.66715148j
   6.95674365-2.06146729j  3.60918254+0.08356593j -5.93251879+2.08605328j
   0.58780338-0.73765227j  4.6115309 -1.32716014j -4.64853451+1.73270074j]] 

